Add missing header bitops.h
xps@xps-XPS-12-9Q33:~/Desktop/hid-rmi-master$ make
make -C /lib/modules/3.11.0-19-generic/build SUBDIRS=/home/xps/Desktop/hid-rmi-master modules
make[1]: Entering directory /usr/src/linux-headers-3.11.0-19-generic'
CC [M] /home/xps/Desktop/hid-rmi-master/hid-rmi.o
/home/xps/Desktop/hid-rmi-master/hid-rmi.c: In function ‘rmi_gen_mask’:
/home/xps/Desktop/hid-rmi-master/hid-rmi.c:464:2: error: implicit declaration of function ‘GENMASK’ [-Werror=implicit-function-declaration]
return GENMASK(irq_count + irq_base - 1, irq_base);
^
cc1: some warnings being treated as errors
make[2]: *** [/home/xps/Desktop/hid-rmi-master/hid-rmi.o] Error 1
make[1]: *** [_module_/home/xps/Desktop/hid-rmi-master] Error 2
make[1]: Leaving directory/usr/src/linux-headers-3.11.0-19-generic'
make: *** [default] Error 2


Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>